# target programming language
language: java

# JDK versios support
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - develop
    
# run tests, findbugs, pmd and friends using Ant, Maven or Gradle
script: 
  - mvn clean package
  - mvn test
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
