# target programming language
language: java

# JDK versios support
jdk:
  - oraclejdk8

branches:
  only:
    - master
    - develop

#clone project for tests
before_script:
  - git clone https://github.com/lincolnrocha/bank-sys.git
  - ll

# run tests, findbugs, pmd and friends using Ant, Maven or Gradle
script: 
  - mvn clean package
  - mvn test
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

# notifications
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
  on_success: always 
  on_failure: always
  on_start: change   # default: never
  on_cancel: always # default: always
  on_error: always
